name: Bug Report
description: File a report to help us improve PCM
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: How can we make this happen ourselves?
      placeholder: |
        1. Start platform with scripts/start-platform.sh
        2. Call endpoint ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Java version, Docker version, etc.
      placeholder: macOS 14.2, Java 21, Docker 24.0.7
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or stack traces.
      render: shell
